cmake_minimum_required(VERSION 3.22.0)
project(task_6_3_figure)
add_executable (
	task_6_4_figure
	task_3.cpp
	figure.cpp
	figure.h
	equilateral_triangle.cpp
	equilateral_triangle.h
	isosceles_triangle.cpp
	isosceles_triangle.h
	parallelogram.cpp
	parallelogram.h
	quadrangle.cpp
	quadrangle.h
	rectangle_figure.cpp
	rectangle_figure.h
	rhombus.cpp
	rhombus.h
	right_triangle.cpp
	right_triangle.h
	square.cpp
	square.h
	triangle.cpp
	triangle.h
)